/**
 * Micro-Dream Trigger API
 * POST: Placeholder endpoint (actual generation happens in enrichment worker)
 * This endpoint is called by reflection save but does nothing now
 * The enrichment worker handles the actual micro-dream generation after post-enrichment
 */

import { NextRequest, NextResponse } from 'next/server';

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { ownerId } = body;

    if (!ownerId) {
      return NextResponse.json({
        error: 'Missing ownerId',
        code: 'VALIDATION_FAILED',
      }, { status: 400 });
    }

    // Just return success - worker handles everything
    console.log('🌙 Micro-dream check called (worker handles generation)');

    return NextResponse.json({
      ok: true,
      message: 'Micro-dream will be generated by worker after post-enrichment',
    });

  } catch (error) {
    console.error('❌ Micro-dream check error:', error);
    
    return NextResponse.json({
      error: 'Internal error',
      details: error instanceof Error ? error.message : 'Unknown',
    }, { status: 500 });
  }
}
